services:
    bootstrap:
        container_name: mosona-manager-bootstrap
        image: alpine:3.23
        command: ["/bin/sh", "/init/fetch_release.sh"]
        environment:
            GITHUB_OWNER: ${GITHUB_OWNER}
            GITHUB_REPO: ${GITHUB_REPO}
            RELEASE_TAG: ${RELEASE_TAG}
            BACKEND_ASSET_AMD64: ${BACKEND_ASSET_AMD64}
            BACKEND_ASSET_ARM64: ${BACKEND_ASSET_ARM64}
            FRONTEND_ZIP_ASSET: ${FRONTEND_ZIP_ASSET}
        volumes:
            - ./init:/init:ro
            - app_bin:/out/bin
            - frontend_dist:/out/frontend
        restart: "no"

    # Postgres
    postgres:
        container_name: mosona-manager-postgres
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d:ro
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 3s
            retries: 30

    # Redis
    redis:
        container_name: mosona-manager-redis
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 30

    # InfluxDB 2
    influxdb:
        container_name: mosona-manager-influxdb
        image: influxdb:2.8-alpine
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
            DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
        volumes:
            - influx_data:/var/lib/influxdb2
#        ports:
#            - "${INFLUX_PORT}:8086"
        healthcheck:
            test: [ "CMD-SHELL", "curl -fsS http://127.0.0.1:8086/health | grep -q '\"status\":\"pass\"'" ]
            interval: 5s
            timeout: 3s
            retries: 60

    # APP
    app:
        container_name: mosona-manager-app
        build:
            context: .
            dockerfile: Dockerfile.app
        image: mosona-manager-app:local
        depends_on:
            bootstrap:
                condition: service_completed_successfully
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            influxdb:
                condition: service_healthy
        environment:
            HOST: 0.0.0.0
            PORT: 8080

            # Postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASS: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB}

            # Redis
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASS: ""

            # InfluxDB
            INFLUXDB_URL: "http://influxdb:8086"
            INFLUXDB_ORG: ${INFLUX_ORG}
            INFLUXDB_BUCKET: ${INFLUX_BUCKET}
            INFLUXDB_TOKEN: ${INFLUX_TOKEN}

            # FRONTEND
            FRONTEND_DIR: /srv/frontend
        volumes:
            - app_bin:/srv/bin:ro
            - frontend_dist:/srv/frontend:ro
            - app_data:/var/lib/mosona-manager
        command: ["/srv/bin/mosona-manager"]
        working_dir: /var/lib/mosona-manager
        ports:
            - "${APP_PORT}:8080"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "/srv/bin/mosona-manager health | grep -q ok"]
            interval: 10s
            timeout: 3s
            retries: 30

volumes:
    pg_data:
    redis_data:
    influx_data:
    app_bin:
    frontend_dist:
    app_data:
